#
# This file generates autogenerated sql fetch model files
#
# TODO:
# - Generate a file for each table in the database
# - Generate common functions using an interface
print("Generating sql core...")